name: frontend CI/CD

on:
  push:
    branches:
      - temp
  pull_request:
    branches:
      - temp

jobs:
  # 잡 전체에 대한 이름 (custom 가능)
  gateway-CICD:
    # ubuntu linux 준비 -> 해장 작업이 진행되는 베이스 OS 지정
    runs-on: ubuntu-latest
    # 개별 작업 단계 지정
    steps:
      - name: Github Repository 내 파일들 checkout(불러오기) 수행
        uses: actions/checkout@v4


      - name: 파일 압축
        run: |
          echo "압축 시작 전 파일 확인"
          ls -a
          echo "압축 시작"
          tar --exclude='./.git' --ignore-failed-read -czvf run.tar.gz ./
          echo "압축 완료..."
          ls -a

      - name: EC2에 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: run.tar.gz
          target: /home/ubuntu/frontend/demo

      - name: SSH로 ec2에 접속 후, 서버 가동
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            ls -l /home/ubuntu/frontend/demo
            mv /home/ubuntu/frontend/demo/run.tar.gz /home/ubuntu/frontend/run.tar.gz
            cd /home/ubuntu/frontend
            fuser -k -n tcp 3000 || true
            tar -xzvf run.tar.gz
            npm install
            npm start > ./output.log 2>&1 &
            rm -rf /home/ubuntu/changeService/demo